### ISSUE TITLE
'EGHL.framework' was built for iOS + iOS Simulator.

### ISSUE THREAD

**Issue by Poojapandey89** [eGHL/reactnative-eghl#19]
Hi,
 I am facing this issue while integrating in iOS.
 Building for iOS Simulator, but the linked and embedded framework 'EGHL.framework' was built for iOS + iOS Simulator.
 
 Please suggest the solution, need asap.

**Comment by Shyan-GHL** [comment]
Reason
Starting in Xcode 11.0, Apple recommended against using a single .framework file to bundle a binary framework or library for multiple platforms, although they still allowed it. As of Xcode 12.3, however, Apple no longer allows this; instead, you must use an .xcframework file. To support running a project on an iOS simulator, versions of the Agora SDK earlier than v3.3.0 bundle a library for multiple platforms in a .framework file, so .framework files are identified by Xcode as a prohibited configuration when you use an iOS simulator to build a project

Solution
In Xcode, navigate to TARGETS > Project Name > Build Settings > Build Options menu, and set Validate Workspace as Yes.
